# Generated by Django 6.1 on 2026-08-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
