import uuid

from django.db import models

from progress.models import QuizAttempt
from users.models import Student


class OfflineSyncRecord(models.Model):
    """
    Tracks quiz attempts uploaded by a device
    after being completed offline.

    client_attempt_id is generated by the
    frontend/mobile app before synchronization.

    It allows retries without creating duplicate
    QuizAttempt records.
    """

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("synced", "Synced"),
        ("failed", "Failed"),
    ]

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name="offline_sync_records",
    )

    client_attempt_id = models.UUIDField(
        help_text=(
            "Unique attempt ID generated on "
            "the student's device."
        ),
    )

    device_id = models.CharField(
        max_length=200,
        blank=True,
        default="",
    )

    quiz_attempt = models.OneToOneField(
        QuizAttempt,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="offline_sync_record",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    client_created_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=(
            "Time the attempt was completed "
            "on the offline device."
        ),
    )

    received_at = models.DateTimeField(
        auto_now_add=True,
    )

    synced_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    error_message = models.TextField(
        blank=True,
        default="",
    )

    class Meta:
        ordering = [
            "-received_at",
        ]

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "student",
                    "client_attempt_id",
                ],
                name=(
                    "unique_student_"
                    "offline_attempt"
                ),
            )
        ]

    def __str__(self):
        return (
            f"{self.student.user.username} - "
            f"{self.client_attempt_id} - "
            f"{self.status}"
        )