# Generated by Django 6.1 on 2026-08-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_grade_alter_chapter_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(help_text='Simple explanation of the topic.')),
                ('key_concepts', models.TextField(blank=True, help_text='Important ideas the student should remember.')),
                ('easy_method', models.TextField(blank=True, help_text='Simple step-by-step method for solving problems.')),
                ('worked_example', models.TextField(blank=True, help_text='A worked example with the solution.')),
                ('common_mistakes', models.TextField(blank=True, help_text='Common mistakes students should avoid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content', to='courses.topic')),
            ],
        ),
    ]
