# Generated by Django 6.1 on 2026-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_academicyear_board_alter_grade_options_grade_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="subject",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("core", "Core Subject"),
                    ("first_language", "First Language"),
                    ("second_language", "Second Language"),
                    ("third_language", "Third Language"),
                    ("optional", "Optional / Skill Subject"),
                ],
                default="core",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("grade", "name", "subject_type", "language"),
                name="unique_subject_per_grade_type_language",
            ),
        ),
    ]
