# Generated by Django 6.1 on 2026-08-25 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("progress", "0002_answer"),
        ("users", "0005_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_attempt_id",
                    models.UUIDField(
                        help_text="Unique attempt ID generated on the student's device."
                    ),
                ),
                ("device_id", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client_created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time the attempt was completed on the offline device.",
                        null=True,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "quiz_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_sync_record",
                        to="progress.quizattempt",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_records",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "client_attempt_id"),
                        name="unique_student_offline_attempt",
                    )
                ],
            },
        ),
    ]
