# Generated by Django 6.1 on 2026-08-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_grade_alter_chapter_options_alter_topic_options_and_more'),
        ('users', '0004_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.grade'),
        ),
    ]
