# Generated by Django 6.1 on 2026-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_subject_options_subject_display_order_and_more"),
        ("users", "0005_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="selected_subjects",
            field=models.ManyToManyField(
                blank=True, related_name="selected_students", to="courses.subject"
            ),
        ),
    ]
